### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
main:
    - identifier: home
      name: Accueil
      url: /
      weight: -100
      pre: home
      params:
        newTab: false
