import type { FitLevel, GapLevel } from "$utils/fit/schema"

/**
 * All UI chrome for the fit report.
 *
 * The model writes analysis; the application writes every label, heading and
 * verdict word. Keeping them here means the report can be rendered in the
 * visitor's language (the model reports which one it used) without the model
 * ever emitting interface text.
 */

export type UiLocale = "fr" | "en"

export const labels = {
	en: {
		heading: "Would I be a good fit for you?",
		intro:
			"Paste a job listing, project brief, or describe what you need. I’ll compare it with my documented experience — including the gaps.",
		inputLabel: "The role, project or need",
		placeholder: "Paste the job listing or describe the project…",
		submit: "Assess the fit",
		submitting: "Reading your brief…",
		preparing: "Loading…",
		stop: "Stop",
		again: "Start over",
		hint: "⌘/Ctrl + Enter to submit",
		counter: (n: number, max: number) => `${n.toLocaleString("en")} / ${max.toLocaleString("en")}`,
		working: "Assembling the assessment",
		sections: {
			summary: "Verdict",
			needs: "What you seem to need",
			evidence: "Relevant evidence",
			precedentSingle: "Closest precedent",
			precedentPatterns: "Transferable patterns",
			gaps: "Gaps",
			questions: "Worth asking me",
		},
		similar: "What was similar",
		transfers: "What transfers",
		different: "What was different",
		whyItMatters: "Why it matters here",
		caveat: "Limit of this evidence",
		viewProject: "See on the portfolio",
		contact: "Get in touch",
		openProject: (title: string) => `Open the full ${title} project`,
		closeProject: "Close",
		projectDetails: "Project details",
		disclaimer:
			"Generated by a language model from my documented portfolio. It is one grounded reading, not an objective score — and it is allowed to conclude that I’m not the right person.",
		fitLevels: {
			strong: "Strong fit",
			promising: "Promising fit",
			mixed: "Mixed fit",
			weak: "Weak fit",
		} satisfies Record<FitLevel, string>,
		gapLevels: {
			adjacent: "Adjacent experience",
			"ramp-up": "Plausible ramp-up",
			none: "No evidence",
		} satisfies Record<GapLevel, string>,
		errors: {
			method_not_allowed: "Something went wrong with that request. Please try again.",
			bad_request: "Something went wrong with that request. Please try again.",
			input_too_short: "That’s a bit short. Add a few sentences about the role or project.",
			input_too_long: "That’s too long to analyse. Please paste the most relevant part.",
			not_configured: "The assessment isn’t available right now. Please try again later.",
			upstream_error: "The assessment failed midway. Your text is still here — try again.",
			generic: "The assessment failed midway. Your text is still here — try again.",
		},
	},
	fr: {
		heading: "Est-ce que je serais fait pour vous ?",
		intro:
			"Collez une offre d’emploi, un brief de projet, ou décrivez votre besoin. Je le compare à mon expérience documentée — lacunes comprises.",
		inputLabel: "Le poste, le projet ou le besoin",
		placeholder: "Collez l’offre d’emploi ou décrivez le projet…",
		submit: "Évaluer",
		submitting: "Lecture de votre brief…",
		preparing: "Chargement…",
		stop: "Arrêter",
		again: "Recommencer",
		hint: "⌘/Ctrl + Entrée pour envoyer",
		counter: (n: number, max: number) => `${n.toLocaleString("fr")} / ${max.toLocaleString("fr")}`,
		working: "Rédaction de l’analyse",
		sections: {
			summary: "Verdict",
			needs: "Ce dont vous semblez avoir besoin",
			evidence: "Éléments pertinents",
			precedentSingle: "Précédent le plus proche",
			precedentPatterns: "Compétences transférables",
			gaps: "Lacunes",
			questions: "À me demander",
		},
		similar: "Ce qui était semblable",
		transfers: "Ce qui se transfère",
		different: "Ce qui différait",
		whyItMatters: "Pourquoi c’est pertinent ici",
		caveat: "Limite de cet élément",
		viewProject: "Voir dans le portfolio",
		contact: "Me contacter",
		openProject: (title: string) => `Ouvrir le projet ${title} en entier`,
		closeProject: "Fermer",
		projectDetails: "Détail du projet",
		disclaimer:
			"Généré par un modèle de langage à partir de mon portfolio documenté. C’est une lecture argumentée, pas une note objective — et il a le droit de conclure que je ne suis pas la bonne personne.",
		fitLevels: {
			strong: "Correspondance forte",
			promising: "Correspondance prometteuse",
			mixed: "Correspondance mitigée",
			weak: "Correspondance faible",
		} satisfies Record<FitLevel, string>,
		gapLevels: {
			adjacent: "Expérience adjacente",
			"ramp-up": "Montée en compétence plausible",
			none: "Aucun élément",
		} satisfies Record<GapLevel, string>,
		errors: {
			method_not_allowed: "La requête a échoué. Réessayez.",
			bad_request: "La requête a échoué. Réessayez.",
			input_too_short: "C’est un peu court. Ajoutez quelques phrases sur le poste ou le projet.",
			input_too_long: "C’est trop long à analyser. Collez la partie la plus pertinente.",
			not_configured: "L’analyse n’est pas disponible pour le moment. Réessayez plus tard.",
			upstream_error: "L’analyse s’est interrompue. Votre texte est conservé — réessayez.",
			generic: "L’analyse s’est interrompue. Votre texte est conservé — réessayez.",
		},
	},
} as const

export type Labels = (typeof labels)[UiLocale]

/**
 * Maps the endpoint's error code to a sentence. Anything unrecognised — a
 * network failure, a proxy error page — falls back to the generic message
 * rather than showing the raw response body.
 */
export function errorMessage(t: Labels, error: Error | undefined) {
	if (!error) return undefined
	const code = error.message.trim() as keyof Labels["errors"]
	return t.errors[code] ?? t.errors.generic
}
