# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Animus"
license = "MIT"
licenselink = "https://github.com/aureliendossantos/animus/blob/master/LICENSE"
description = ""
homepage = "http://example.com/"
tags = ["blog", "personal", "light", "dark", "portfolio", ]
features = []
min_version = "0.101.0"

[author]
  name = "Aurélien Dos Santos"
  homepage = "https://aureliendossantos.com"
