mainSections:
    - post
    - photos
    - formation
featuredImageField: image
rssFullContent: true
favicon:

footer:
    since: 2015
    customText:

dateFormat:
    published: 02 Jan 2006
    lastUpdated: 02 Jan 2006

sidebar:
    emoji: 💭
    subtitle: "Bonjour, je suis Aurélien et vous êtes sur mon blog.<br>[A propos](/about)"
    avatar:
        enabled: true
        local: true
        src: img/avatar.jpg

article:
    math: false
    toc: false
    readingTime: true
    license:
        enabled: true
        default: Sous licence CC BY-NC-SA 4.0

widgets:
    enabled:
        - search
        - archives
        - tag-cloud
    archives:
        limit: 6
    tagCloud:
        limit: 20

opengraph:
    twitter:
        # Your Twitter username
        site: ooooorelien
        # Available values: summary, summary_large_image
        card: summary_large_image

# Default image for Open Graph tag
defaultImage:
    opengraph:
        enabled: false
        local: false
        src:

colorScheme:
    # Display toggle
    toggle: true
    # Available values: auto, light, dark
    default: auto

imageProcessing:
    cover:
        enabled: false
    content:
        enabled: false
