// Serif
import "@fontsource/lora"
import "@fontsource/vollkorn"
// Sans serif
import "@fontsource/lato"
import "@fontsource/noto-sans"
import "@fontsource/nunito"
import "@fontsource/nunito/700.css"
import "@fontsource/sofia-sans"
import "@fontsource/space-grotesk"
import "@fontsource/space-grotesk/700.css"
import "@fontsource/urbanist"
import "@fontsource/urbanist/400-italic.css"
import "@fontsource/work-sans"
import "@fontsource/work-sans/300.css"
import "@fontsource/work-sans/500.css"
import "@fontsource/work-sans/600.css"
import "@fontsource/work-sans/700.css"
import "@fontsource/work-sans/400-italic.css"
import "@fontsource/work-sans/700-italic.css"
// Monospace
import "@fontsource/source-code-pro"
import "@fontsource/space-mono"
import "@fontsource/space-mono/400-italic.css"
// Custom fonts
import "$styles/fonts/anek-latin.css"
import "$styles/fonts/et-book.css"
import "$styles/fonts/source-serif.css"
